spring.application.name=Backend-I
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=yash@2006
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false

whatsapp.token=EAAWl4IiZCI1wBQ9lHJPU6u897nHeyOHeJqePFiK2qMf2MO079OMZC0Gi3xUbiq3ePT79W8aUGZBu361uYfV13bwYNXtSMUuaB4qltpPQmchy2UePXujZAJQ5Iozbm9pKU7ZCvqdh5o7mHMIGrwKOpUGGb3ktzoSWGjk05PPIjwOUgny4yKwm5wMPlsdY799zxZBzZB8eDWjSFhBk9KKeZCBsA0XghZCS4zuchh8eE5uhZAVeVnk5JVhSCHB1Ema6rPX613my5ZBU5B0bRgnTfOlbb086WatUwZDZD
whatsapp.phone-id=833084629898439


